### PR TITLE
Use Vault

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-17.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-17.dev.beta.nhschoices.net)

**Comment by adamgraves-choices** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-17.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-17.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-17.dev.beta.nhschoices.net)

**Pull request closed without merging**
