### PR TITLE
Feature/add stuff

### PR DESCRIPTION
**Pull request by st3v3nhunt**
This gets the app working and provides these routes:

* `./redirect` which will redirect the new gp profile page if the referer is 'valid' otherwise a page with some text that will need to be finalised will be displayed
* Adding `?debug` to the route will show the headers and the where the redirect will go to if it isn't undefined

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-redirect-pr-1.dev.c2s.nhschoices.net](http://gp-redirect-pr-1.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-redirect-pr-1.dev.c2s.nhschoices.net](http://gp-redirect-pr-1.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-redirect-pr-1.dev.c2s.nhschoices.net](http://gp-redirect-pr-1.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-redirect-pr-1.dev.c2s.nhschoices.net](http://gp-redirect-pr-1.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-redirect-pr-1.dev.c2s.nhschoices.net](http://gp-redirect-pr-1.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-redirect-pr-1.dev.c2s.nhschoices.net](http://gp-redirect-pr-1.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-redirect-pr-1.dev.c2s.nhschoices.net](http://gp-redirect-pr-1.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-redirect-pr-1.dev.c2s.nhschoices.net](http://gp-redirect-pr-1.dev.c2s.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployed to [http://gp-redirect-pr-1.dev.c2s.nhschoices.net](http://gp-redirect-pr-1.dev.c2s.nhschoices.net)

**Comment by neilbmclaughlin** [comment]
Looks good to me.

**Review by neilbmclaughlin — APPROVED** [review]

**Pull request merged**
