### PR TITLE
Feature/stop snyk

### PR DESCRIPTION
**Pull request by st3v3nhunt**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-27.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-27.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-27.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-27.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-27.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-27.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-27.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-27.dev.beta.nhschoices.net)

**Review by markysoft — APPROVED** [review]
LGTM

**Pull request merged**
