### PR TITLE
Deployment upgrade

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-15.dev.beta.nhschoices.net)

**Comment by st3v3nhunt** [comment]
@adamgraves-choices Have a look at #16 and merge in if you are happy. It fixes the build problems this branch is having.

**Comment by c2s-dev** [comment]
:rocket: deployment of gp-redirect succeeded (http://gp-redirect-pr-15.dev.beta.nhschoices.net)

**Review by st3v3nhunt — APPROVED** [review]
LGTM

**Pull request merged**
